### PR TITLE
Fix unit usage

### LINKED ISSUE #242: Question: Transfer Rate MBps or Mbps?
android_file_transfer_transfer_rate

I have a question. Was that MBps or Mbps? 

Before the app, I use to use FTP for transferring larger files. I was getting 25-27 MBps via nautilus (< 1GB files). 

Please let me know.

### PR DESCRIPTION
**Pull request by huupoke12**
Resolve #242 
By the way, the metric prefix for kilo is `k`, not `K`, which equal to 1000. If you want to use 1024 base, you should use [binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix) instead.

### CODE REVIEW

File: qt/progressdialog.cpp [hunk 1]
```diff
@@ -97,15 +97,15 @@ void ProgressDialog::setValue(float current)
...
-	static constexpr double Gb = 1000 * Mb;
-	if (speed < 2 * Mb)
-		ui->speedLabel->setText(tr("Speed: %1 Kb/s").arg(speed / Kb, 0, 'f', 1));
-	else if (speed < 2 * Gb)
-		ui->speedLabel->setText(tr("Speed: %1 Mb/s").arg(speed / Mb, 0, 'f', 1));
+	static constexpr double kB = 1000;
+	static constexpr double MB = 1000 * kB; // k, M, G are metric prefixes
+	static constexpr double GB = 1000 * MB; // 1024 is for binary prefixes
+	if (speed < 2 * MB)
+		ui->speedLabel->setText(tr("Speed: %1 kB/s").arg(speed / kB, 0, 'f', 1));
```
Comment (whoozle) [inline qt/progressdialog.cpp:104]: Speed: %1 kB/s

Can you fix translations as well please? (except probably russian, it's in cyrillic, I'll fix it myself) they are in qt/translations

**Comment by huupoke12** [comment]
About the translations, I recommend not including the binary files (.qm) into the repository, they should be compiled on the local machine. And I also recommend to include a translation project file so it can be updated to match. Please see [this example](https://doc.qt.io/qt-5/qtlinguist-hellotr-example.html) for more information. You can include those commands in to the makefile to make it run automatically when compiling.
